/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginReceptionRouteImport } from './routes/login.reception'
import { Route as LoginRoleRouteImport } from './routes/login.$role'
import { Route as AppRoleRouteImport } from './routes/app.$role'
import { Route as AppRoleIndexRouteImport } from './routes/app.$role.index'
import { Route as AppRolePageRouteImport } from './routes/app.$role.$page'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginReceptionRoute = LoginReceptionRouteImport.update({
  id: '/login/reception',
  path: '/login/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoleRoute = LoginRoleRouteImport.update({
  id: '/login/$role',
  path: '/login/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoleRoute = AppRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleIndexRoute = AppRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoleRoute,
} as any)
const AppRolePageRoute = AppRolePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppRoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$role': typeof AppRoleRouteWithChildren
  '/login/$role': typeof LoginRoleRoute
  '/login/reception': typeof LoginReceptionRoute
  '/login/': typeof LoginIndexRoute
  '/app/$role/$page': typeof AppRolePageRoute
  '/app/$role/': typeof AppRoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login/$role': typeof LoginRoleRoute
  '/login/reception': typeof LoginReceptionRoute
  '/login': typeof LoginIndexRoute
  '/app/$role/$page': typeof AppRolePageRoute
  '/app/$role': typeof AppRoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$role': typeof AppRoleRouteWithChildren
  '/login/$role': typeof LoginRoleRoute
  '/login/reception': typeof LoginReceptionRoute
  '/login/': typeof LoginIndexRoute
  '/app/$role/$page': typeof AppRolePageRoute
  '/app/$role/': typeof AppRoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$role'
    | '/login/$role'
    | '/login/reception'
    | '/login/'
    | '/app/$role/$page'
    | '/app/$role/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login/$role'
    | '/login/reception'
    | '/login'
    | '/app/$role/$page'
    | '/app/$role'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$role'
    | '/login/$role'
    | '/login/reception'
    | '/login/'
    | '/app/$role/$page'
    | '/app/$role/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoleRoute: typeof LoginRoleRoute
  LoginReceptionRoute: typeof LoginReceptionRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/reception': {
      id: '/login/reception'
      path: '/login/reception'
      fullPath: '/login/reception'
      preLoaderRoute: typeof LoginReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$role': {
      id: '/login/$role'
      path: '/login/$role'
      fullPath: '/login/$role'
      preLoaderRoute: typeof LoginRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$role': {
      id: '/app/$role'
      path: '/$role'
      fullPath: '/app/$role'
      preLoaderRoute: typeof AppRoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$role/': {
      id: '/app/$role/'
      path: '/'
      fullPath: '/app/$role/'
      preLoaderRoute: typeof AppRoleIndexRouteImport
      parentRoute: typeof AppRoleRoute
    }
    '/app/$role/$page': {
      id: '/app/$role/$page'
      path: '/$page'
      fullPath: '/app/$role/$page'
      preLoaderRoute: typeof AppRolePageRouteImport
      parentRoute: typeof AppRoleRoute
    }
  }
}

interface AppRoleRouteChildren {
  AppRolePageRoute: typeof AppRolePageRoute
  AppRoleIndexRoute: typeof AppRoleIndexRoute
}

const AppRoleRouteChildren: AppRoleRouteChildren = {
  AppRolePageRoute: AppRolePageRoute,
  AppRoleIndexRoute: AppRoleIndexRoute,
}

const AppRoleRouteWithChildren =
  AppRoleRoute._addFileChildren(AppRoleRouteChildren)

interface AppRouteChildren {
  AppRoleRoute: typeof AppRoleRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppRoleRoute: AppRoleRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoleRoute: LoginRoleRoute,
  LoginReceptionRoute: LoginReceptionRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
